### ISSUE TITLE
Does not seem to work on macOS Monetery

### ISSUE THREAD

**Issue by ad-si** [jdek/openwith#1]
Exact version is: 12.1, x86_64

**Comment by jdek** [comment]
did you build it yourself or just download the first release? I just tested it on 12.1 and it works for me.
If the latter, then try this version (no changes to code just re-built on 12.1): [openwith-0.0.1-2.tar.gz](https://github.com/jdek/openwith/files/7868381/openwith-0.0.1-2.tar.gz)

**Comment by ad-si** [comment]
I mean it works in the sense, that it seems to successfully execute:

```txt
$ ./openwith Numbers xlsx
xlsx (org.openxmlformats.spreadsheetml.sheet) -> Numbers
xlsx (com.microsoft.excel.openxmlformats.spreadsheetml.sheet) -> Numbers
```
But afterwards when I open an xlsx file, it still uses Excel!

I tried with a version I built myself and with the one you provided.

**Comment by jdek** [comment]
My guess is that it is working but the bundle identifier for Numbers is not `Numbers` but `com.apple.iWork.Numbers` instead. Try `openwith com.apple.iWork.Numbers xlsx`.

**Comment by ad-si** [comment]
Ah, yes, that works! Sorry, I was assuming I have to use the same identifiers as with `open -a`. Shouldn't `openwith` log an error if you use an incorrect identifier? And is there an easier way to find out the bundle id then to check the `Info.plist` file in the app folder?

**Comment by jdek** [comment]
I don't think there should be any error, it works as expected (i.e. one of the points of the utility is to be able to set application handlers before the application is installed fully). I considered adding a `openwith -a` flag such that the name can be used but the API to make this possible has been [deprecated]. You could probably use something like `osascript -e 'id of app "Numbers"'` to find it more easily.

[deprecated]: https://developer.apple.com/documentation/appkit/nsworkspace/1533992-fullpath

**Comment by ad-si** [comment]
Ok 👍 

Did you forget the `… app …`  part in the readme?

[$ osascript -e 'id of "mpv"'](https://github.com/jdek/openwith/blob/9d30898cde5e4c4e7314e71dba2ed707cf08833e/README.md?plain=1#L17)

**Comment by jdek** [comment]
Ah, yep thanks.
